name: React dev build
on:
  push: # master Branch에서 push 이벤트가 일어났을 때만 실행
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code.
        uses: actions/checkout@master

      - name: Cache node modules # node modules 캐싱
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Install Dependencies # 의존 파일 설치
        run: npm install

      - name: Build # React Build
        run: npm run build
        env:
          CI: ''
          # REACT_APP_HOST: ${{ secrets.REACT_APP_HOST }}
          # REACT_APP_ROOT_URL: ${{ secrets.REACT_APP_ROOT_URL }}
          # REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
          # REACT_APP_AUTHORITY: ${{ secrets.REACT_APP_AUTHORITY }}
          # REACT_APP_REDIRECT_URI: ${{ secrets.REACT_APP_REDIRECT_URI }}
          # REACT_APP_CHAT_SERVER_URI: ${{secrets.REACT_APP_CHAT_SERVER_URI }}

      - name: Deploy # S3에 배포하기
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            build s3://app-dev.rubric.im
